version: '3.3'

services:
  client:
    build:
      context: ./client/
      dockerfile: dev.Dockerfile
    image: client
    container_name: client
    volumes:
      - ./client/:/usr/src/app/
      - /usr/src/app/node_modules
    links:
      - server:server
    depends_on:
      - server
    expose:
      - 8080

  node-iot-generator:
    build:
      context: ./node-iot-generator/
      dockerfile: dev.Dockerfile
    image: node-iot-generator
    container_name: node-iot-generator
    volumes:
      - ./node-iot-generator/:/usr/src/api/
      - /usr/src/api/node_modules
    env_file: ./node-iot-generator/.env
    expose:
      - 3000

  # server:
  #   build:
  #     context: ./server/
  #     dockerfile: dev.Dockerfile
  #   image: server
  #   container_name: server
  #   env_file: ./server/.env
  #   expose:
  #     - 5000
